version: "3.7"
services:
  postgres:
    container_name: postgres5
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=hellopizza
      - POSTGRES_DB=database
    ports:
      - 5432:5432
  app:
    container_name: app
    restart: always
    image : hellopizza/project1:3
    ports:
      - 5000:5000
    volumes:
      - .:/app
    depends_on:
      - postgres
    entrypoint: ["python3","app.py"]

